Kitchen_Service/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Kitchen_Service import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
]

kitchen/urls.py
from django.urls import path

from kitchen.views import (index,
                           DishTypeListView,
                           DishTypeCreateView,
                           DishTypeUpdateView,
                           DishTypeDeleteView, DishListView, DishDetailView, DishCreateView, DishUpdateView,
                           DishDeleteView, CookListView, CookDetailView, CookCreateView,
                           CookUpdateView, CookDeleteView, ToggleAssignToDishView
                           )

app_name = "kitchen"

urlpatterns = [
    path("", index, name="index"),
    path(
        "dish_types/",
        DishTypeListView.as_view(),
        name="dish-type-list"),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "dish/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        ToggleAssignToDishView.as_view(),
        name="toggle-dish-assign"

    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    )
]

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse


# Create your models here.
class DishType(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Dish type name",
        help_text="Enter the name of the dish type (e.g. Soup, Dessert)."
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "dish type"
        verbose_name_plural = "dish types"

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(
        default=0,
        verbose_name="Years of experience",
        help_text="Enter the years of experience.",
        validators=[
            MinValueValidator(
                0,
                message="Years Of Experience can`t be negative."
        ),
            MaxValueValidator(
                40,
                message="Experience cannot exceed 40 years.")
        ]
    )

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def get_absolute_url(self):
        return reverse(
            "kitchen:cook-detail",
            kwargs={"pk": self.pk}
        )

    def __str__(self):
        return (f"{self.username} ({self.first_name} {self.last_name}), "
                f"years of experience: {self.years_of_experience}")


class Dish(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Dish name",
        help_text="Enter the name of the dish.",
    )
    description = models.TextField(
        max_length=500,
        verbose_name="Dish description",
        help_text="Enter the description of the dish.",)
    price = models.DecimalField(
        decimal_places=2,
        max_digits=10,
        verbose_name="Dish price",
        help_text="Enter the price of the dish.",
        validators=[
            MinValueValidator(
                0.01,
                message="Price must be greater than 0"
            )
        ]
    )
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.SET_NULL,
        null=True,
    )
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ("-price",)

    def __str__(self):
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Dish, Cook


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "years_of_experience")


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        ),
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        ),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import DishForm, CookCreationForm, CookSearchForm, DishSearchForm, DishTypeSearchForm, CookUpdateForm
from kitchen.models import Cook, DishType, Dish


# Create your views here.
@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_cooks = Cook.objects.all().count()
    num_dish_types = DishType.objects.all().count()
    num_dishes = Dish.objects.all().count()

    context = {
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
    }

    return render(request, "kitchen/index.html", context=context)

class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_types"
    paginate_by = 5

    def get_context_data(
            self, *, object_list=None, **kwargs
    ):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        context["search_form"] = DishTypeSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return DishType.objects.filter(name__icontains=name)
        return DishType.objects.all()


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    context_object_name = "dish_list"
    queryset = Dish.objects.select_related("dish_type")

    def get_context_data(
        self, *, object_list=None, **kwargs
    ):
        context = super(DishListView, self).get_context_data(**kwargs)
        context["search_form"] = DishSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(
        self, *, object_list=None, **kwargs
    ):
        context = super(CookListView, self).get_context_data(**kwargs)
        context["search_form"] = CookSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        username = self.request.GET.get("username")
        if username:
            return Cook.objects.filter(username__icontains=username)
        return Cook.objects.all()


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class ToggleAssignToDishView(LoginRequiredMixin, generic.View):
    def post(self, request, pk):
        cook = request.user
        dish = get_object_or_404(Dish, pk=pk)

        if cook.dishes.filter(pk=pk).exists():
            cook.dishes.remove(dish)
        else:
            cook.dishes.add(dish)

        return redirect("kitchen:dish-detail", pk=pk)

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cook?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:cook-detail' pk=cook.id %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook.username }}
    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>

  <div class="ml-3">
    <h4>Dishes</h4>

    {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Name:</strong> {{ dish.name }}</p>
        <p><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'kitchen:cook-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/cook_list.html
 {% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
      Cook list
      <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>
  <form method="get" action="" class="form-inline">
  {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-secondary">
  </form>

    {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
    {% for cook in cook_list %}
      <tr>
        <td>{{ cook.id }}</td>
        <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
        <td>{{ cook.first_name }}</td>
        <td>{{ cook.last_name }}</td>
        <td>{{ cook.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no cooks in the restaurant.</p>
    {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:dish-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Dish type: {{ dish.dish_type.name }}</p>
  <p>Price: {{ dish.price }}</p>
  <p>Description: {{ dish.description }}</p>
  <h2>
    Cooks

    {% if dish in user.dishes.all %}
      <form action="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" method="post" style="display: inline;">
  {% csrf_token %}
        <button type="submit" class="btn btn-danger link-to-page">
          Delete me from this dish
        </button>
      </form>
    {% else %}
      <form action="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" method="post" style="display: inline;">
  {% csrf_token %}
        <button type="submit" class="btn btn-success link-to-page">
          Assign me to this dish
        </button>
      </form>
    {% endif %}

  </h2>
  <hr>
  <ul>
    {% for cook in dish.cooks.all %}
      <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'kitchen:dish-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>
    Dish list
    <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline" >
  {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-secondary">
  </form>
  {% if dish_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for dish in dish_list %}
        <tr>
          <td>
              {{ dish.id }}
          </td>
          <td>
            <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
          </td>
          <td>
              <a href="{% url 'kitchen:dish-update' pk=dish.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'kitchen:dish-delete' pk=dish.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no dishes yet.</p>
  {% endif %}
{% endblock %}

templates/kitchen/dishtype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:dish-type-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dishtype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dishtype_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>
    Dish type list
    <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form method="get" action="" >
  {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-secondary">
  </form>
  {% if dish_types %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for dish_type in dish_types %}
        <tr>
          <td>
              {{ dish_type.id }}
          </td>
          <td>
              {{ dish_type.name }}
          </td>
          <td>
              <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no dish types yet.</p>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">

  <title>
    Django Material Kit  - Presentation | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="presentation-page bg-gray-200">

  {% include 'includes/navigation.html' %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/unnamed.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Kitchen Service Home</h1>
            <p class="lead text-white mt-3">Welcome to the Restaurant!</p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1" countTo={{ num_cooks }}>0</span></h1>
                  <h5 class="mt-3">Cooks</h5>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2" countTo={{ num_dish_types }}>0</span></h1>
                  <h5 class="mt-3">Dish Types</h5>

                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state3" countTo={{ num_dishes }}>0</h1>
                  <h5 class="mt-3">Dishes</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- -------   END PRE-FOOTER 2 - simple social line w/ title & 3 buttons    -------- -->
  </div>

  <footer class="footer pt-5 mt-5">
    <div class="container">
      <div class=" row">

        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              &copy; Kitchen Service — Anastasiia Pohonets
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
</body>

</html>